# Generated by Django 5.0.2 on 2026-02-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ID пользователя')),
                ('items', models.JSONField(verbose_name='Товары в корзине')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('process', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=50, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
